"use client";

import { useState } from "react";
import { CookieConsent } from "@/components/cookie-consent";

const formats = [
  { id: "chronological", number: "01", title: "Chronological", text: "Lead with your strongest recent experience.", best: "Best for steady careers" },
  { id: "functional", number: "02", title: "Functional", text: "Make your skills the main story.", best: "Best for career changers" },
  { id: "hybrid", number: "03", title: "Combination", text: "Balance skills with proven experience.", best: "Best for professionals" },
  { id: "targeted", number: "04", title: "Targeted", text: "Tailor every word to one opportunity.", best: "Best for competitive roles" },
  { id: "academic", number: "05", title: "Academic CV", text: "Show research, education and achievements.", best: "Best for academia & students" },
];

export default function Home() {
  const [active, setActive] = useState("chronological");
  const [menu, setMenu] = useState(false);
  const selected = formats.find((format) => format.id === active) ?? formats[0];
  return <main>
    <nav className="nav"><a className="brand" href="#top"><span className="brand-mark">P</span>PATHWAY</a><div className={menu ? "nav-links open" : "nav-links"}><a href="#formats">Resume types</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="/signin">Sign in</a><a className="button small" href="/signup">Start building</a></div><button className="menu" aria-label="Open menu" onClick={() => setMenu(!menu)}>☰</button></nav>

    <section className="hero" id="top"><span className="float-sticker one">✦ ATS READY</span><span className="float-sticker two">YOUR ERA →</span><div className="eyebrow">YOUR CAREER, CLEARER</div><h1>Make your next<br/><em>move matter.</em></h1><p>PATHWAY helps you create a resume that feels like you—and gets past the systems standing in your way.</p><div className="hero-actions"><a className="button" href="/signup">Build my resume <span>→</span></a><a className="text-link" href="#how">See how it works <span>↓</span></a></div><div className="trust"><div className="avatars"><i>R</i><i>S</i><i>M</i><i>A</i></div><span>Trusted by <b>12,000+</b> ambitious people</span></div><div className="resume-card"><div className="card-top"><span className="dot"></span><span className="dot"></span><span className="dot"></span><span className="card-label">YOUR RESUME</span></div><div className="card-body"><div className="portrait">AR</div><div><div className="line long"></div><div className="line medium"></div><div className="line short"></div></div></div><div className="score"><span>ATS readiness</span><b>94<span>%</span></b><div className="progress"><i></i></div></div><div className="card-footer"><span>Strategist</span><span>2026</span></div></div></section>

    <section className="formats" id="formats"><div className="section-heading"><div><div className="eyebrow">FIND YOUR FORMAT</div><h2>Every path deserves<br/>the right <em>shape.</em></h2></div><p>Start with the format that makes your experience look its best. Change it whenever your story evolves.</p></div><div className="format-grid">{formats.map((format) => <button className={active === format.id ? "format active" : "format"} key={format.id} onClick={() => setActive(format.id)}><span className="format-number">{format.number}</span><h3>{format.title}</h3><p>{format.text}</p><span className="best">{format.best} <b>↗</b></span></button>)}</div><div className="format-preview"><div className="preview-paper"><div className="paper-name">ALEX RIVERA</div><div className="paper-role">PRODUCT DESIGNER</div><div className="paper-rule"></div><div className="paper-columns"><div><strong>{selected.title.toUpperCase()}</strong><p>Selected based on the path you want to take, not just the jobs you’ve had.</p></div><div><strong>EXPERIENCE</strong><p>Senior Product Designer<br/>Studio North · 2023—Now</p></div></div></div><div className="preview-copy"><span className="eyebrow">SELECTED FORMAT</span><h3>{selected.title} resume</h3><p>{selected.text} PATHWAY will guide your structure, highlight what matters, and make it easy to tailor.</p><a href="/signup" className="text-link">Use this format <span>→</span></a></div></div></section>

    <section className="how" id="how"><div className="eyebrow">A CLEARER WAY FORWARD</div><h2>Less guessing.<br/><em>More momentum.</em></h2><div className="steps"><article><span>01</span><h3>Tell us where you’ve been</h3><p>Import a current resume or answer a few thoughtful questions.</p></article><article><span>02</span><h3>Choose your direction</h3><p>Our AI recommends a format and helps tailor it to your goal.</p></article><article><span>03</span><h3>Apply with confidence</h3><p>Export an ATS-ready resume, polished for the people reading it.</p></article></div></section>

    <section className="pricing" id="pricing"><div className="pricing-head"><div><div className="eyebrow">SIMPLE, HONEST PRICING</div><h2>Invest in your<br/><em>next chapter.</em></h2></div><p>Start free. Upgrade only when you need more support.</p></div><div className="price-grid"><article><span className="plan">Explorer</span><h3>Free</h3><p>For getting started with clarity.</p><ul><li>2 editable resume drafts</li><li>All five resume types</li><li>3 AI suggestions monthly</li><li>No PDF or DOCX export</li></ul><a href="/signup" className="text-link">Start building free →</a></article><article className="featured"><span className="popular">MOST POPULAR</span><span className="plan">Momentum</span><h3>₹159 <small>/ month</small></h3><p>For focused job seekers who want more yeses.</p><ul><li>Unlimited resumes</li><li>AI writing assistance</li><li>Full ATS analysis</li><li>PDF & DOCX exports</li></ul><a href="/signup?plan=momentum" className="button">Upgrade when ready →</a></article><article><span className="plan">Premium</span><h3>₹499 <small>/ month</small></h3><p>For every ambitious move.</p><ul><li>Everything in Momentum</li><li>Targeted job matching</li><li>Cover letters</li><li>Priority support</li></ul><a href="/signup?plan=premium" className="text-link">Explore Premium →</a></article></div></section>
    <footer><a className="brand" href="#top"><span className="brand-mark">P</span>PATHWAY</a><span>© 2026 PATHWAY. Build what’s next.</span><div><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a><a href="/cookies">Cookies</a><a href="/terms">Terms</a><a href="/refunds">Refunds</a></div></footer><CookieConsent />
  </main>;
}
